import generated from './featuredDecks.json'

// Featured/starter decks for the 7 official Riftbound champions. These are
// legal, on-theme community builds (not Riot's exact preconstructed lists,
// which aren't publicly available card-for-card). Generated by
// scripts/build-featured-decks.mjs.

export interface FeaturedDeck {
  id: string
  name: string
  champion: string
  group: 'Champion Deck' | 'Proving Grounds'
  archetype: string
  legendId: string
  main: Record<string, number>
  runes: Record<string, number>
  battlefields: string[]
  mainCount: number
  runeCount: number
}

export const FEATURED_DECKS = generated as unknown as FeaturedDeck[]
